var pfData=[
    {
        "id":28,
        "title":"卸妆湿巾(油性)",
        "comment":"油性卸妆湿巾液，可用于湿巾产品中",
        "type":"cleanclear",
        "materialPrice":200,
        "methodPrice":100,
        "code":"CWS0110"
    },
    {
        "id":29,
        "title":"防晒乳液SPF2 PA++",
        "comment":"SPF25，PA++ 防晒乳液，肤感轻柔舒适。",
        "type":"pc",
        "materialPrice":800,
        "methodPrice":800,
        "code":"PRS0190"
    },
    {
        "id":30,
        "title":"化妆水",
        "comment":"为肌肤补水，时刻保持肌肤滋润。",
        "type":"pc",
        "materialPrice":180,
        "methodPrice":100,
        "code":"PYS0200"
    },
    {
        "id":31,
        "title":"美肤保湿乳",
        "comment":"添加美白和保湿成分，能够提亮肤色减退暗沉，及时补充水分。",
        "type":"pc",
        "materialPrice":580,
        "methodPrice":500,
        "code":"PRS0210"
    },
    {
        "id":32,
        "title":"洗衣液",
        "comment":"经济又实用的洗衣液配方，操作简单，成本低廉。",
        "type":"household",
        "materialPrice":100,
        "methodPrice":100,
        "code":"HYQ0180"
    },
    {
        "id":33,
        "title":"舒缓精华液",
        "comment":"有效缓解皮肤过敏产生的不适，缓解炎症减轻红斑。",
        "type":"pc",
        "materialPrice":100,
        "methodPrice":80,
        "code":"PYS0010"
    },
    {
        "id":34,
        "title":"修护霜",
        "comment":"含有修复肌肤细胞，促进细胞新生的成份。",
        "type":"pc",
        "materialPrice":300,
        "methodPrice":150,
        "code":"PGS0020"
    },
    {
        "id":35,
        "title":"美白乳液",
        "comment":"多种美白成份复配，使美白效果更明显。",
        "type":"pc",
        "materialPrice":150,
        "methodPrice":100,
        "code":"PRS0030"
    },
    {
        "id":36,
        "title":"美白精华液",
        "comment":"多种美白成份复配，制成精华液方便涂擦使用。",
        "type":"pc",
        "materialPrice":120,
        "methodPrice":80,
        "code":"PYS0040"
    },
    {
        "id":37,
        "title":"美白面膜",
        "comment":"添加有效美白成分，同时避免产品变黄变暗，延长作用时间。",
        "type":"pc",
        "materialPrice":350,
        "methodPrice":300,
        "code":"PWS0050"
    },
    {
        "id":38,
        "title":"美白面膜（无防腐宣称）",
        "comment":"添加有防腐功效的原料，该成份不在防腐剂目录中，可宣称不含防腐剂。",
        "type":"pc",
        "materialPrice":1000,
        "methodPrice":500,
        "code":"PWS0051"
    },
    {
        "id":39,
        "title":"抗老化乳液",
        "comment":"添加六胜肽，有效缓解肌肤细胞老化，恢复年轻态。",
        "type":"pc",
        "materialPrice":800,
        "methodPrice":450,
        "code":"PRS0060"
    },
    {
        "id":40,
        "title":"润肤啫喱",
        "comment":"透明啫喱产品，外观晶莹，肤感好。",
        "type":"pc",
        "materialPrice":280,
        "methodPrice":200,
        "code":"PTS0070"
    },
    {
        "id":41,
        "title":"爽肤水",
        "comment":"低端成本配方，操作简便。",
        "type":"pc",
        "materialPrice":250,
        "methodPrice":100,
        "code":"PYS0080"
    },
    {
        "id":42,
        "title":"温和洁面乳",
        "comment":"温和的含氨基酸表活的洗面配方，洗后肤感舒适不紧绷，不刺激。",
        "type":"cleanclear",
        "materialPrice":580,
        "methodPrice":350,
        "code":"CRS0090"
    },
    {
        "id":43,
        "title":"按摩油",
        "comment":"按摩精油，含天然精油成份和热感剂，能宣称减脂塑身。",
        "type":"pc",
        "materialPrice":500,
        "methodPrice":200,
        "code":"PLS0100"
    },
    {
        "id":44,
        "title":"按摩乳液（W/O）",
        "comment":"油包水结构的配方，可做按摩肌肤产品使用。",
        "type":"pc",
        "materialPrice":1200,
        "methodPrice":800,
        "code":"PRS0120"
    },
    {
        "id":45,
        "title":"须后水",
        "comment":"中档男士产品，能有效缓解须后的不适感。",
        "type":"pc",
        "materialPrice":750,
        "methodPrice":400,
        "code":"PYS0130"
    },
    {
        "id":46,
        "title":"保湿乳液（仿丝芙兰）",
        "comment":"仿丝芙兰莫诺伊花香保湿身体乳液配方。",
        "type":"pc",
        "materialPrice":2500,
        "methodPrice":1800,
        "code":"PRS0140"
    },
    {
        "id":47,
        "title":"晚霜",
        "comment":"肤感舒适，外观光亮。",
        "type":"pc",
        "materialPrice":800,
        "methodPrice":350,
        "code":"PGS0150"
    },
    {
        "id":48,
        "title":"遮瑕乳(W/O)",
        "comment":"添加色素，可修饰肌肤斑痕，起到遮瑕效果，油包水结构，使颜色不易脱落。",
        "type":"pc",
        "materialPrice":1500,
        "methodPrice":1000,
        "code":"PRS0121"
    },
    {
        "id":49,
        "title":"厨房清洁湿巾",
        "comment":"方便好用的厨房清洁产品，不刺激，无异味。",
        "type":"household",
        "materialPrice":800,
        "methodPrice":500,
        "code":"HWK0130"
    },
    {
        "id":50,
        "title":"去指甲油片",
        "comment":"快速去除指甲油，不留痕迹，是出口欧洲的产品配方。",
        "type":"cleanclear",
        "materialPrice":600,
        "methodPrice":200,
        "code":"CWS0140"
    },
    {
        "id":51,
        "title":"卸妆湿巾（温和型）",
        "comment":"仿国内知名品牌配方。",
        "type":"cleanclear",
        "materialPrice":800,
        "methodPrice":800,
        "code":"CWS0150"
    },
    {
        "id":52,
        "title":"车用清洁剂",
        "comment":"汽车清洁用品，清洗干净，温和不损伤车身。",
        "type":"household",
        "materialPrice":900,
        "methodPrice":600,
        "code":"HYQ0160"
    },
    {
        "id":53,
        "title":"全效家具光亮喷剂",
        "comment":"能有效提高家具光泽，对家具不会造成伤害。",
        "type":"household",
        "materialPrice":850,
        "methodPrice":700,
        "code":"HYJ0170"
    }
];